// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb5zDJ7AkuDMZo8cfjw_j0cLMmTwEwk0M',
    appId: '1:620058299996:web:a68c507e3839e832e52099',
    messagingSenderId: '620058299996',
    projectId: 'taskit-proj',
    authDomain: 'taskit-proj.firebaseapp.com',
    storageBucket: 'taskit-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRGz_yP64wekPkzqPh6SUXgTMDPeUA63U',
    appId: '1:620058299996:android:a7d820528b999e75e52099',
    messagingSenderId: '620058299996',
    projectId: 'taskit-proj',
    storageBucket: 'taskit-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8g60a9EmsagBB9GieFl8DSomiKltohWY',
    appId: '1:620058299996:ios:4b0055e71a46f246e52099',
    messagingSenderId: '620058299996',
    projectId: 'taskit-proj',
    storageBucket: 'taskit-proj.appspot.com',
    iosClientId: '620058299996-8pccsjnsqd2hc4u1sjvffusumvlb4kqt.apps.googleusercontent.com',
    iosBundleId: 'dev.jasoncao.taskit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8g60a9EmsagBB9GieFl8DSomiKltohWY',
    appId: '1:620058299996:ios:4b0055e71a46f246e52099',
    messagingSenderId: '620058299996',
    projectId: 'taskit-proj',
    storageBucket: 'taskit-proj.appspot.com',
    iosClientId: '620058299996-8pccsjnsqd2hc4u1sjvffusumvlb4kqt.apps.googleusercontent.com',
    iosBundleId: 'dev.jasoncao.taskit',
  );
}
